### ISSUE TITLE
Packagist package missing

### ISSUE THREAD

**Issue by kachkaev** [CiscoVE/PiwikBundle#1]
Hi guys,

Could you please register the bundle on packagist? It's currently difficult to install it with composer.

**Comment by thoroc** [comment]
@kachkaev Hi, this has not been maintained, so I would be a bit reluctant to publish it on packagist. Have you tried https://github.com/devhelp/piwik-bundle as an alternative?

-thoroc

**Comment by kachkaev** [comment]
Thanks for the advice!
